### ISSUE TITLE
Add ability to pass test sheet from cli

### ISSUE THREAD

**Issue by kannangce** [techconative/Restel#25]
At the moment the test sheet path has to be passed via environment variable. Add support to pass it via command line args. So that the user can execute the jar without having to set the environment variable.

Related change required in,
- Readme.
- Start scripts.
- Getting rid of usage of environment variable.

**Comment by Anzo52** [comment]
@kannangce where would sheet path be passed as a parameter/arg?

**Comment by kannangce** [comment]
> @kannangce where would sheet path be passed as a parameter/arg?

The sheet will have to be passed to the main class. The intention is, user should be able to run it from the jar, like 
`java -jar <jar name> <main class> <excel sheet>`

**Comment by kannangce** [comment]
@Anzo52 do you need any help on getting this done?

**Comment by Anzo52** [comment]
@kannangce probably. I'm still trying increase my knowledge of this area (polymorphism?/interoperability?). As far as I know, any argument after <main class> gets passed to the main class, is there a way to utilize that?

**Comment by kannangce** [comment]
That's right, whatever we pass after main class will be available as argument for the main method, there you might have to set the system env  used for spreadsheet.

**Comment by Anzo52** [comment]
I found this insightful: https://stackoverflow.com/a/8123107

**Comment by kannangce** [comment]
Sure @Anzo52!

**Comment by kannangce** [comment]
Hi @Anzo52,

Please let me know if you need any help on this. We can do pair programming if needed.

**Comment by kannangce** [comment]
@Anzo52 Since we're planning to include this in our upcoming release. We're taking it up ourself.
Sorry that we had to rush in. If you're interested, please check out other [`good first issue` tagged issues](https://github.com/techconative/Restel/labels/good%20first%20issue) that we have.

**Comment by bharathyes** [comment]
Added support with #41
